name: Build and Comment PR

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  pull-requests: write  # Обязательно: разрешаем боту писать в PR

jobs:
  check_optimization:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure and Build
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Run Optimisation
        id: run_opt
        shell: bash
        run: |
          # Запускаем и сохраняем вывод в переменную окружения
          ./build/Release/BPLA_Optimisation.exe > result.txt
          
          # Записываем содержимое файла в специальный буфер GitHub
          echo "OPT_RESULT<<EOF" >> $GITHUB_ENV
          cat result.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Post Comment to PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### 🤖 Отчет о результатах оптимизации
            По результатам прогона в режиме **Release**:
            
            ${{ env.OPT_RESULT }}
            
            ---
            _Сборка выполнена автоматически. Если результат F вас устраивает, PR можно мержить._